# based on https://ctan.asis.ai/support/latexmk/example_rcfiles/
# If equal to 1, generate a pdf version of the document using pdflatex
$pdf_mode = 1;
$postscript_mode = $dvi_mode = 0;

$warnings_as_errors = 1;

$pdflatex = "pdflatex --shell-escape %O %S";

@default_files = ('main.tex');
